services:
  mysql:
    image: mysql:8.0
    container_name: relational-db-test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test_root_password
      MYSQL_DATABASE: UsersDB
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
